export interface IProductRequest{
    name:string;
    category:any;
    brand:string;
    subCategory:any;
    description:string;
    price:number;
    imagePath:string;
    color:string;
    size:string;
    width:string;
    height:string;
    count:number;
}
export interface IProductResponce{
    id:string;
    name:string;
    brand:string;
    category:any;
    subCategory:any;
    description:string;
    price:number;
    imagePath:string;
    color:string;
    size:string;
    width:string;
    height:string;
    count:number;
}